Add Issue templates
langningchen/XMOJ-Script pull request #121
Opened 2023-08-26 15:24 UTC by PythonSmall-Q

Add issue templates

2023-08-26 15:25 UTC, PythonSmall-Q commented
那个cloudflare pages为啥要check啊啊啊……

2023-08-26 15:26 UTC, PythonSmall-Q commented
效果
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/4c17b55c-3d7e-4205-bd10-6fde4ce533c7)

2023-08-26 15:26 UTC, PythonSmall-Q commented
在https://github.com/PythonSmall-Q/XMOJ-Script/issues/new/choose里面可以试试

2023-08-26 23:44 UTC, langningchen commented
嗯，我看看

2023-08-26 23:44 UTC, langningchen commented
我应该要对你PR的代码进行一些更改

2023-08-26 23:50 UTC, langningchen requested changes

2023-08-26 23:50 UTC, langningchen commented on .github/ISSUE_TEMPLATE/bug.yml
> +labels: [· Bug, 新反馈]
新反馈的Label去掉

2023-08-26 23:50 UTC, langningchen commented on .github/ISSUE_TEMPLATE/bug.yml
> +    label: 日志与附件
这个改一下吧，改成检查控制台错误

2023-08-26 23:50 UTC, langningchen commented on .github/ISSUE_TEMPLATE/bug.yml
> +    placeholder: "Version"
我觉得应该增加怎么查看版本号的详细说明

2023-08-26 23:50 UTC, langningchen commented on .github/ISSUE_TEMPLATE/ch.yml
> +name: "优化建议"
我认为优化建议没有必要，因为它和新功能建议基本上重复我

2023-08-26 23:50 UTC, langningchen commented on .github/ISSUE_TEMPLATE/feature.yml
> +labels: [· 新功能, 新反馈]
Label设为Enhancement

2023-08-26 23:50 UTC, langningchen commented on .github/ISSUE_TEMPLATE/feature.yml
> +    - label: "我已知晓还没做的新功能真的太多了，忙不过来 qwq……"
这个......嗯，先别加了吧
毕竟多提点Issue，慢慢做也没事

2023-08-26 23:51 UTC, langningchen commented
我现在改不了代码，到下午才能改，所以提了六个审查意见

2023-08-26 23:51 UTC, langningchen commented
如果你下午还没有改，那我就帮你改掉了

2023-08-27 02:21 UTC, PythonSmall-Q commented
@langningchen 修改了

2023-08-27 02:21 UTC, PythonSmall-Q commented
你看看

2023-08-27 02:56 UTC, langningchen commented
再看看

2023-08-27 02:59 UTC, langningchen commented
你怎么把Bug的标签直接删掉了？应该是把“新功能”删掉就行了 @PythonSmall-Q

2023-08-27 03:00 UTC, langningchen requested changes
Bug.yml 再加上 Bug 标签就行了

2023-08-27 03:01 UTC, langningchen commented on .github/ISSUE_TEMPLATE/bug.yml
> +labels: [· Bug, 新反馈]
> 新反馈的Label去掉

我没有说 Bug 的Label 也去掉

2023-08-27 03:47 UTC, PythonSmall-Q commented
@langningchen changed

2023-08-27 04:42 UTC, PythonSmall-Q commented
@langningchen @boomzero

2023-08-27 05:13 UTC, langningchen commented
Good @PythonSmall-Q

2023-08-27 05:14 UTC, langningchen commented
就是为什么这个 Cloudflare Pages 过不去……

2023-08-27 05:14 UTC, langningchen commented
那就强制 Merge 吧，希望别处锅

2023-08-27 05:15 UTC, merged