Add rating
langningchen/XMOJ-Script pull request #32
Opened 2023-08-14 13:34 UTC by boomzero

As of now, it will only display on the user page, but I will add username colors soon

2023-08-14 13:44 UTC, langningchen commented
I may be slow to response these days because I will focus on my homework. If you have further questions, you can add my WeChat.

2023-08-14 13:45 UTC, langningchen commented
WeChat ID has been sent to you via "XMOJ Mail", aka "XMOJ Short Message".

2023-08-14 13:47 UTC, boomzero commented
> WeChat ID has been sent to you via "XMOJ Mail", aka "XMOJ Short Message".



> I am looking forward to the usernames color!

Any ideas on the rating formula, currently I am just guessing

2023-08-14 14:05 UTC, boomzero commented
完了, 不小心 format 了...

2023-08-14 14:07 UTC, boomzero commented
![](https://cdn.luogu.com.cn/upload/image_hosting/rhrdx74s.png)

2023-08-14 14:14 UTC, boomzero commented
<img width="1232" alt="rank" src="https://github.com/langningchen/XMOJ-Script/assets/85378277/20350764-badb-4f91-ac22-30746c81b428">

2023-08-14 14:15 UTC, boomzero commented
I added red, yellow, green and blue

2023-08-14 14:15 UTC, boomzero commented
Of course colors need to be added in other places

2023-08-14 23:24 UTC, langningchen commented
> 完了, 不小心 format 了...

没事

2023-08-14 23:26 UTC, langningchen commented
> Of course colors need to be added in other places

我觉得如果每个页面都去获取这些信息是不行的，你应该在本地留一个缓存，比如说一周再更新一次

2023-08-14 23:58 UTC, langningchen commented
我刚才一直都忘记Submit Review了，一直是Pending的状态

2023-08-15 00:04 UTC, langningchen requested changes

2023-08-15 00:04 UTC, langningchen commented on XMOJ.user.js
> +                                    }
所以除了格式化，你就改了这一些，对吗？

2023-08-15 00:04 UTC, langningchen commented on XMOJ.user.js
> +                                    }
如果是，其他的我就撤销更改了

2023-08-15 01:58 UTC, boomzero commented on XMOJ.user.js
> +                                    }
Umm, 加了 Getrating

2023-08-15 01:59 UTC, boomzero commented on XMOJ.user.js
> +                document.querySelector("#statics > tbody > tr:nth-child(1) > td:nth-child(2)").innerHTML += "rating：" + (await getRating(UserID).then());
so what should we call it

2023-08-15 02:16 UTC, langningchen commented on XMOJ.user.js
> +                                    }
Getrating？

2023-08-15 02:16 UTC, langningchen commented on XMOJ.user.js
> +                                    }
哦，明白了

2023-08-15 02:19 UTC, langningchen approved these changes

2023-08-15 02:24 UTC, merged

2023-08-15 02:41 UTC, boomzero commented on XMOJ.user.js
> +            const textResponse = await response.text();
? 我还没改啊

2023-08-15 02:53 UTC, langningchen commented
@boomzero 还有我一会儿改一下你的Rating计算方式，我之前没仔细看，现在才发现你的计算方式是 解决/提交，而我想改成 正确/提交

2023-08-15 03:24 UTC, boomzero commented
有bug啊, 显示Uncaught SyntaxError: export declarations may only appear at top level of a module www.xmoj.tech:3242
    n moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:22
    eval moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:23
    b moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:44
    then moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:15
    b moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:44
    jo moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:46
    Io moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:45
    forEach self-hosted:203
    Mt moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:8
    t moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:9
    Io moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:40
    Yo moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:58
    Vo moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:58
    En moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:15
    forEach self-hosted:203
    Mt moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:8
    t moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:9
    En moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:15
    o moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:54
    apply self-hosted:2366
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.sys.mjs:635
    wrapPromise resource://gre/modules/ExtensionCommon.sys.mjs:899
但是我提交前测试没有问题

2023-08-15 03:25 UTC, boomzero commented
> @boomzero 还有我一会儿改一下你的Rating计算方式，我之前没仔细看，现在才发现你的计算方式是 解决题目数/提交次数，而我想改成 解决次数/提交次数

那不会有人刷AC率吗, xmoj直接爆炸

2023-08-15 03:28 UTC, boomzero commented
> 有bug啊, 显示Uncaught SyntaxError: export declarations may only appear at top level of a module [www.xmoj.tech:3242](http://www.xmoj.tech:3242) n moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:22 eval moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:23 b moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:44 then moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:15 b moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:44 jo moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:46 Io moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:45 forEach self-hosted:203 Mt moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:8 t moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:9 Io moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:40 Yo moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:58 Vo moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:58 En moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:15 forEach self-hosted:203 Mt moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:8 t moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:9 En moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:15 o moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/content.js:54 apply self-hosted:2366 applySafeWithoutClone resource://gre/modules/ExtensionCommon.sys.mjs:635 wrapPromise resource://gre/modules/ExtensionCommon.sys.mjs:899 但是我提交前测试没有问题

你看一下最新版, 怎么回事, 我昨天测试正常的啊

2023-08-15 03:28 UTC, boomzero commented
@langningchen

2023-08-15 03:38 UTC, boomzero commented
content.js 是什么啊

2023-08-15 03:39 UTC, boomzero commented
Can you reproduce this?

2023-08-15 03:46 UTC, langningchen commented
这个Bug是我的依赖出问题了，不是我出的问题

2023-08-15 03:46 UTC, langningchen commented
我刚才也发现了

2023-08-15 03:46 UTC, langningchen commented
> > @boomzero 还有我一会儿改一下你的Rating计算方式，我之前没仔细看，现在才发现你的计算方式是 解决题目数/提交次数，而我想改成 解决次数/提交次数
> 
> 那不会有人刷AC率吗, xmoj直接爆炸

应该不会

2023-08-15 03:47 UTC, langningchen commented
我本地已经改好了，但是还没有push

2023-08-15 03:49 UTC, langningchen commented
不过这又要你们重新安装了 @PythonSmall-Q @boomzero

2023-08-15 03:49 UTC, langningchen commented
现在正在自动化发布

2023-08-15 03:54 UTC, langningchen commented
就是[这个](https://github.com/drudru/ansi_up/releases/tag/v6.0.0)讨厌的ANSI_UP仓库，三个小时前刚发布了一个新版本，而且还对前端有BUG！

2023-08-15 03:55 UTC, langningchen commented
他升级什么ES6，原来还能向下兼容浏览器前端运行，现在只能在服务器上面运行了

2023-08-15 03:56 UTC, langningchen commented
我得过一会儿找一个替代品，或者使用旧版本

2023-08-15 04:08 UTC, boomzero commented
> 我得过一会儿找一个替代品，或者使用旧版本

6,我还以为是我的pr搞的

2023-08-15 04:11 UTC, boomzero commented
> > 我得过一会儿找一个替代品，或者使用旧版本
> 
> 6,我还以为是我的pr搞的
你能开一个 issue 吗

2023-08-15 04:13 UTC, langningchen commented
怎么开？

2023-08-15 04:13 UTC, langningchen commented
说啥？

2023-08-15 04:13 UTC, langningchen commented
要么你来开吧

2023-08-15 04:15 UTC, boomzero commented
> > > @boomzero 还有我一会儿改一下你的Rating计算方式，我之前没仔细看，现在才发现你的计算方式是 解决题目数/提交次数，而我想改成 解决次数/提交次数
> > 
> > 
> > 那不会有人刷AC率吗, xmoj直接爆炸
> 
> 应该不会

还要算AC题目数, 不然新用户直接rating最高

2023-08-15 04:16 UTC, langningchen commented
> 还要算AC题目数, 不然新用户直接rating最高

好吧，确实

2023-08-15 04:16 UTC, langningchen commented
如果XMOJ能开放尝试题目数就好了

2023-08-15 04:17 UTC, langningchen commented
或者我们有什么方法能知道用户的尝试题目数？

2023-08-15 04:19 UTC, boomzero commented
@langningchen  https://github.com/langningchen/XMOJ-Script/issues/33

2023-08-15 04:20 UTC, langningchen commented
哦，好的

2023-08-15 04:20 UTC, langningchen commented
谢谢

2023-08-15 04:20 UTC, boomzero commented
> 或者我们有什么方法能知道用户的尝试题目数？

没办法, 只能一题一题爬

2023-08-15 04:20 UTC, boomzero commented
> 谢谢

你加一下标签 upstream-issue

2023-08-15 04:21 UTC, boomzero commented
或者类似的

2023-08-15 04:21 UTC, langningchen commented
我加了“upstream-issue”

2023-08-15 04:21 UTC, langningchen commented
> > 或者我们有什么方法能知道用户的尝试题目数？
> 
> 没办法, 只能一题一题爬

一题一题爬肯定不行，因为有可能有的题他做了，对他开放，而对我们不开放

2023-08-15 04:23 UTC, langningchen commented
所以只能到时候再找一找XMOJ有没有BUG泄露了这个数据了

2023-08-15 04:23 UTC, boomzero commented
不过http://www.xmoj.tech/problemstatus.php?id= 全部开放

2023-08-15 04:23 UTC, boomzero commented
不管题库里有没有这题

2023-08-15 04:24 UTC, langningchen commented
哦，好像是啊

2023-08-15 04:24 UTC, langningchen commented
一题一题、一页一页来这样太浪费服务器资源了，我再想想

2023-08-15 04:26 UTC, boomzero commented
可以加上 通过题目数/小明所有题目数(大约6000)

2023-08-15 04:26 UTC, boomzero commented
6406

2023-08-15 04:27 UTC, langningchen commented
这个所有题目数会增长的

2023-08-15 04:27 UTC, langningchen commented
我先去吃饭了

2023-08-15 04:28 UTC, boomzero commented
可以爬吧, 好像最新的题都是月赛?

2023-08-15 05:12 UTC, boomzero commented
> 这个所有题目数会增长的

可以设为6000, 反正没有人做过所有题, 除了std

2023-08-15 05:45 UTC, langningchen commented
> 可以爬吧, 好像最新的题都是月赛?

确实

2023-08-15 05:51 UTC, boomzero commented
Also can you make yellow and red names bold

2023-08-15 05:52 UTC, boomzero commented
Just like luogu

2023-08-15 05:53 UTC, boomzero commented
And the criteria for red names is too high, only a few people can get a AC rate over 50%

2023-08-15 05:54 UTC, boomzero commented
~~不过好像50%是我设的~~

2023-08-15 06:12 UTC, langningchen commented
> Also can you make yellow and red names bold

可以（如果我记得）

2023-08-15 06:13 UTC, boomzero commented
> > Also can you make yellow and red names bold
> 
> 可以（如果我记得）

Should I write it

2023-08-15 06:13 UTC, langningchen commented
你可以帮我写一下（反正很简单）

2023-08-15 06:14 UTC, langningchen commented
你直接用`<b>`就好了，应该不用CSS的`font-weight`

2023-08-15 06:16 UTC, boomzero commented
> 你可以帮我写一下（反正很简单）

Can you write it? I need to do my homework now.

2023-08-15 06:20 UTC, langningchen commented
我也在做作业。。。

2023-08-15 06:20 UTC, langningchen commented
我还以为你有空呢（

2023-08-15 13:17 UTC, boomzero commented
> 我还以为你有空呢（

az, 6