Update SECURITY.md
langningchen/XMOJ-Script pull request #581
Opened 2023-10-01 08:18 UTC by PythonSmall-Q

2023-10-01 09:18 UTC, langningchen requested changes
如果你要改成中文，那就直接把英文全都去掉吧

2023-10-02 00:41 UTC, boomzero requested changes

2023-10-02 00:41 UTC, boomzero commented on SECURITY.md
>  # Security Policy
把英文去掉? 或者中英文分离(参见code of conduct)

2023-10-02 00:44 UTC, langningchen commented on SECURITY.md
>  # Security Policy
@boomzero 要么你来改吧， @PythonSmall-Q 在认真做题

2023-10-02 01:37 UTC, PythonSmall-Q commented
Ahh是的 @boomzero 你来改。做题中qwq

2023-10-02 02:04 UTC, PythonSmall-Q commented
fixed
同时改了一下readme

2023-10-02 02:04 UTC, PythonSmall-Q commented
@langningchen @boomzero

2023-10-02 02:13 UTC, langningchen submitted a review, later dismissed
更改 README.md 时必须同步更改 index.html

2023-10-02 03:41 UTC, PythonSmall-Q commented
fixed

2023-10-02 03:41 UTC, PythonSmall-Q commented
@langningchen

2023-10-02 03:47 UTC, langningchen approved these changes

2023-10-02 03:47 UTC, langningchen commented
LGTM

2023-10-02 03:47 UTC, PythonSmall-Q commented
Addon Script Changed to match security needs

2023-10-02 03:48 UTC, langningchen approved these changes
Thanks!

2023-10-02 03:48 UTC, PythonSmall-Q commented
/addon-script

2023-10-02 03:49 UTC, PythonSmall-Q commented
Merge? @langningchen

2023-10-02 03:50 UTC, PythonSmall-Q commented
Merge? @langningchen

2023-10-02 03:51 UTC, langningchen commented
可以，Approve了以后都可以Merge

2023-10-02 03:51 UTC, langningchen commented
如果有问题我会 Request Changes

2023-10-02 03:52 UTC, merged