Merge Dev
langningchen/XMOJ-Script pull request #71
Opened 2023-08-24 09:29 UTC by boomzero

有merge conflict...

2023-08-24 09:31 UTC, boomzero commented
> 欸，别着急Merge，等等！

我只是解决一下merge conflict @langningchen

2023-08-24 09:35 UTC, langningchen commented
哦，好吧，这个Conflict是我造的

2023-08-24 09:36 UTC, langningchen approved these changes

2023-08-24 09:36 UTC, langningchen commented
嗯？Conflict没了？

2023-08-24 14:10 UTC, boomzero commented
@langningchen Should I merge this?

2023-08-25 00:34 UTC, langningchen commented
@boomzero 等等！

2023-08-25 00:37 UTC, langningchen requested changes

2023-08-25 00:37 UTC, langningchen commented on README.md
> +
我把它移到前面是因为图片太长了，或者你可以少弄几张图片并且把图片缩小一点

2023-08-25 00:37 UTC, langningchen commented on XMOJ.user.js
> -// @connect      127.0.0.1
这个怎么能删呢？连接一个本地没什么问题的

2023-08-25 00:37 UTC, langningchen commented on XMOJ.user.js
> -            }
复制的功能我还要用！QAQ

2023-08-25 00:37 UTC, langningchen commented on index.html
> -&lt;https://www.gnu.org/licenses/why-not-lgpl.html&gt;.
谢谢！

2023-08-25 00:40 UTC, langningchen commented
这有几个更改不太好，我会退一下

2023-08-25 03:23 UTC, boomzero commented on XMOJ.user.js
> -// @connect      127.0.0.1
因为没有用啊

2023-08-25 03:23 UTC, boomzero commented on XMOJ.user.js
> -            }
直接点申请数据不就行了吗

2023-08-25 03:43 UTC, boomzero commented
?

2023-08-25 05:03 UTC, langningchen commented on XMOJ.user.js
> -// @connect      127.0.0.1
怎么没有用

2023-08-25 05:51 UTC, closed without merging

2023-08-25 05:51 UTC, langningchen commented
@boomzero 你Milestone都还没有实现怎么Merge到master？